### ISSUE TITLE
Remove logback from transitive dependencies

### ISSUE THREAD

**Issue by gavvvr** [johanhaleby/occurrent#154]
When using Occurrent, there is a Logback coming transitively.
I noticed that because now I want to switch to another SLF4J implementation in my project, and there is a warning that multiple implementations of SLF4J is found in classpath.

I inspected the dependencies graph and found out that some components of Occurrent bring Logback transitively. Occurrent as a library should not enforce or bring any particular logger implementation to consumers classpaths and should rather depend on SLF4J only.

**Comment by johanhaleby** [comment]
You're right, I picked logback because I thought everyone was using it today ;) But I'll try to change to slf4j instead.

**Comment by johanhaleby** [comment]
I've fixed it now (I think) :)

**Comment by gavvvr** [comment]
Hi @johanhaleby 
There was a linked PR from me about this. There is no need to include SLF4J at all in 3 out of 3 modules, because you do not even depend on it. Please see #155
