### ISSUE TITLE
Upgrade Mongo native eventsore to Mongo Java driver v5

### ISSUE THREAD

**Issue by gavvvr** [johanhaleby/occurrent#161]
Hi. The new major version of Mongo-java driver (v5) was released. I guess, at least the Mongodb native eventsore module can be already upgraded to it.
Here is the list of breaking changes: https://www.mongodb.com/docs/drivers/java/sync/current/upgrade/#breaking-changes

**Comment by johanhaleby** [comment]
Good find! Thanks again :)

**Comment by gavvvr** [comment]
Spring Data MongoDB also upgrades to v5 native driver in the next minor release (4.3.0) ([src](https://github.com/spring-projects/spring-data-mongodb/issues/4680))

**Comment by gavvvr** [comment]
Hi @johanhaleby 
I guess this should be closed [since 0.19.0](https://github.com/johanhaleby/occurrent/blob/occurrent-0.19.1/changelog.md#0190-2024-05-17) :)

**Comment by johanhaleby** [comment]
Yeah it's done! It's currently using 5.1.1. Thanks for reminding me :)
